plugins {
    id 'java'
    id 'war'
}

group 'ch.ergon.sandro'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    junitVersion = '5.13.2'
}

java {
    sourceCompatibility = '25'
    targetCompatibility = '25'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

dependencies {
    implementation files('libs/my-web-app-lib.jar')
    compileOnly('jakarta.servlet:jakarta.servlet-api:6.1.0')
    testImplementation("org.junit.jupiter:junit-jupiter-api:${junitVersion}")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junitVersion}")
}

test {
    useJUnitPlatform()
}
